name: Deploy to EC2

on: 
  push: 
    branches: 
      - main
         
jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps: 
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Copy Code to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          source: ./
          target: ~/app

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ~/app
            ls -al
            sudo cp -r * /var/www/html/
            sudo systemctl restart nginx

      
